### ISSUE TITLE
RPFM crash

### ISSUE THREAD

**Issue by pretendant** [Frodo45127/rpfm#108] opened 2020-04-19 11:13 UTC
RPFM seems to be running well. I can operate it with no problem, until... I try to browse my folder, like open Packfile, then boom crash. Same with all the thing that open something. To get the folder location of my games in preferences I managed to copy and paste, but when it will come to Save as my files, I don't see how I can work around this.

**Extra info?**
<I'm running the latest version of RPFM, on Windows 8, I can open things from content no problem. I run it as admin.
No error folder is created on this crash so I can't attach any file...>

**Comment by Frodo45127** [comment] 2020-04-19 14:21
mmmm what version of RPFM are you using? I remember seeing that crash on one of the betas for 2.0, but got fixed a couple of weeks ago.

**Comment by pretendant** [comment] 2020-04-19 14:34
Ii'm suing 1.6.2 for windows

**Comment by Frodo45127** [comment] 2020-04-19 22:10
Can you check if the problem is still reproducible with the latest 2.0 beta from here? https://mega.nz/file/aoZj3aqT#uXbAHYVre7aq8jxGP-BDCcwXZKndasJeMkM5digbBPo 

And is there any "error-something.toml" file in RPFM's folder? That's where crashes are logged.

**Comment by Frodo45127** [comment] 2020-05-30 08:46
Closing this, as the crash is probably no longer in the program due to the 2.0 rewrite.

**Closed by Frodo45127** 2020-05-30 08:46 UTC
