### ISSUE TITLE
support TWA's tables

### ISSUE THREAD

**Issue by Trolldemorted** [Frodo45127/rpfm#9] opened 2018-08-12 23:36 UTC
The tables are encrypted indeed, but I think I managed to get the key. You can use [twa_table_decrypt](https://github.com/TotalWarArena-Modding/twa_table_decrypt) or [twa_table_decrypt_lib](https://crates.io/crates/twa_table_decrypt_lib) to decrypt them, but it could be that the ends of the decrypted tables are a bit off because I didn't understand the paddings correctly.

Do you think the decrypted tables look ok? Naturally it would be great if rpfm would display the tables, so I assume we have to create a schema?

**Comment by Frodo45127** [comment] 2018-08-13 12:30
If the tables can be decrypted and it has the same structure than the ones used in other games, an schema is enough to get them to show up in RPFM. For now, we can copy Attila's schema and start from there, as many tables, like the ```kv_*``` ones usually don't change between games.

For what I saw in the other issue, at least the header of the table is like the ones from other games, so... guess there is no problem there. What I'm not sure it that "paddings" you talked about. What paddings did you found?

**Comment by Trolldemorted** [comment] 2018-08-13 13:51
#8 is about the pack files' padding: files in padded packs are always starting at multiples of 8.

The padding I mentioned here is caused by the decryption: At the moment twa_table_decrypt_lib decrypts tables in sets of 8 bytes (just like TWA does), so if the plaintext file's size is not a multiple of 8 we will have a few "garbage" bytes at the end. I'd expect that I can just drop them, but since I don't know where the actual table ends I wanted to hear your opinion first.

**Comment by Frodo45127** [comment] 2018-08-13 14:48
mmmm then don´t think there is a problem. The logic to decode the tables just tries to decode the number of rows there are in the header using the current table definition. If there are extra bytes, the program ignores them as for him, there is nothing more to decode.

**Comment by Frodo45127** [comment] 2018-08-22 01:16
Ok, with one of the last commits, Arena tables are now decrypted and decoded using the schema `schema_are.json`, based on Rome 2 Schema. The schema is not complete (and it's probably not going to be complete, because we don't have an easy way or time to get all the tables done) but for dataminers and others interested in decode and check the tables, it's there.

Something I noticed is I had to get the decrypt function directly from `twa_pack_lib`, as the one from `twa_table_decrypt_lib` only worked for `PFH4` PackFiles (tested with Rome 2 `music.pack`) as it didn't truncated the extra padding bytes. Tables still worked, but judging by the fact that all the "padding" bytes got decrypted as `00`, they need to get remove. So, once you update the `twa_table_decrypt_lib` function to remove those bytes, I'll update this to not have a duplicate of your function and use the one from that crate.

Until then, this issue is done.

**Closed by Frodo45127** 2018-08-22 01:16 UTC
