### ISSUE TITLE
I have found strange values in RPFM table of Warhammer Total War 2: character_skill_level_to_effects_junctions_tables

### ISSUE THREAD

**Issue by Teddybear2020** [Frodo45127/rpfm#154] opened 2021-02-08 16:35 UTC
Hey, I compared values of character_skill_level_to_effects_junctions_tables: Assembly KIT and RPFM

is it ok?

wh_dlc06_skill_dwf_runelord_self_rune_of_hearth_&__home
wh_dlc06_skill_dwf_runelord_self_rune_of_hearth_&__home
wh_dlc06_skill_dwf_runelord_self_rune_of_hearth_&__home
wh_dlc06_skill_dwf_runesmith_self_master_rune_of_oath_&__steel
wh_dlc06_skill_dwf_runesmith_self_master_rune_of_oath_&__steel
wh_dlc06_skill_dwf_runesmith_self_master_rune_of_oath_&__steel
wh_dlc06_skill_dwf_runesmith_self_master_rune_of_wrath_&__ruin
wh_dlc06_skill_dwf_runesmith_self_master_rune_of_wrath_&__ruin
wh_dlc06_skill_dwf_runesmith_self_master_rune_of_wrath_&__ruin
wh_main_skill_dwf_runesmith_self_rune_of_hearth_&__home
wh_main_skill_dwf_runesmith_self_rune_of_hearth_&__home
wh_main_skill_dwf_runesmith_self_rune_of_hearth_&__home
wh_main_skill_dwf_runesmith_self_rune_of_oath_&__steel
wh_main_skill_dwf_runesmith_self_rune_of_oath_&__steel
wh_main_skill_dwf_runesmith_self_rune_of_oath_&__steel
wh_main_skill_dwf_runesmith_self_rune_of_wrath_&__ruin
wh_main_skill_dwf_runesmith_self_rune_of_wrath_&__ruin
wh_main_skill_dwf_runesmith_self_rune_of_wrath_&_ruin

**Comment by Teddybear2020** [comment] 2021-02-08 16:36
> wh_dlc06_skill_dwf_runelord_self_rune_of_hearth_&_home
> wh_dlc06_skill_dwf_runelord_self_rune_of_hearth_&_home
> wh_dlc06_skill_dwf_runelord_self_rune_of_hearth_&_home
> wh_dlc06_skill_dwf_runesmith_self_master_rune_of_oath_&_steel
> wh_dlc06_skill_dwf_runesmith_self_master_rune_of_oath_&_steel
> wh_dlc06_skill_dwf_runesmith_self_master_rune_of_oath_&_steel
> wh_dlc06_skill_dwf_runesmith_self_master_rune_of_wrath_&_ruin
> wh_dlc06_skill_dwf_runesmith_self_master_rune_of_wrath_&_ruin
> wh_dlc06_skill_dwf_runesmith_self_master_rune_of_wrath_&_ruin
> wh_main_skill_dwf_runesmith_self_rune_of_hearth_&_home
> wh_main_skill_dwf_runesmith_self_rune_of_hearth_&_home
> wh_main_skill_dwf_runesmith_self_rune_of_hearth_&_home
> wh_main_skill_dwf_runesmith_self_rune_of_oath_&_steel
> wh_main_skill_dwf_runesmith_self_rune_of_oath_&_steel
> wh_main_skill_dwf_runesmith_self_rune_of_oath_&_steel
> wh_main_skill_dwf_runesmith_self_rune_of_wrath_&_ruin
> wh_main_skill_dwf_runesmith_self_rune_of_wrath_&_ruin
> wh_main_skill_dwf_runesmith_self_rune_of_wrath_&_ruin
>

**Comment by Frodo45127** [comment] 2021-02-08 16:56
It's what ok? I mean.... I'm not seeing what the problem is.

**Comment by Teddybear2020** [comment] 2021-02-08 20:46
I mean you cant find values with &

example:
campaign_group_members_tables = 9710 rows
campaign_group_members Assembly Kit = 4631

![image](https://user-images.githubusercontent.com/73296797/107278959-7c07e500-6a67-11eb-9159-a6bf05152355.png)

![image](https://user-images.githubusercontent.com/73296797/107279111-ab1e5680-6a67-11eb-9669-2308831dc180.png)

**Comment by Teddybear2020** [comment] 2021-02-08 20:50
diplomacy_Subcult_Empire_&_OtherFactionVamp
I think there is only 1 row but RPFM generates 3 rows?

![image](https://user-images.githubusercontent.com/73296797/107279680-67781c80-6a68-11eb-83cf-10b28c3cd651.png)

**Comment by Frodo45127** [comment] 2021-02-09 21:04
RPFM doesn't generate anything. It just reads the data from the file, and shows it. If there are more lines, it probably means the Assembly kit version you have doesn't correspond with the version of the game you have, or the assembly kit does some processing that makes new lines appear when exporting, or CA used a different version of the assembly kit when exporting the tables in the game than the one you have. Are you sure you have both up-to-date?

**Comment by Teddybear2020** [comment] 2021-02-10 18:20
@Frodo45127 
can you check these values?
if you get the same result, you can make the correct conclusion about whether the RPFM reads the data correctly?

**Comment by Frodo45127** [comment] 2021-02-10 19:16
I can confirm you the results you get are the same I get, and are correct. All the tables have a row count, and when decoding RPFM checks that it has that exact amount of rows and that there is no more data from the table to decode, to ensure it's decoded properly. And both checks passed in those tables. It looks to me that those differences are from that last update CA did not so long ago. Probably they didn't updated the assembly kit accordingly.

**Comment by Teddybear2020** [comment] 2021-02-10 20:05
ok, I will be on guard of data integrity

sorry to write here (already created a topic). I beg you to pay attention to the OR-filter. if you can add please.
thank you again for your hard work!

**Comment by Frodo45127** [comment] 2021-03-09 17:28
Closing this, as it was more or less confirmed that it was just that the assembly kit wasn't updated by CA for the last hotfix.

**Closed by Frodo45127** 2021-03-09 17:28 UTC
