### ISSUE TITLE
Message error since last schema update 

### ISSUE THREAD

**Issue by memet13007** [Frodo45127/rpfm#265] opened 2023-08-07 17:29 UTC
**Describe your problem**
using last version of RPFM and Modding total war 3k recently with no problem, then troday a Message error with : Invalid reference "vo_actor_group_generic_any_male_wood_general" in column "voiceover_actor_group" pops since last schema update, when i don't think there is suppose to be one.

**Extra info?**

![Capture d’écran (93)](https://github.com/Frodo45127/rpfm/assets/127595209/5b4f9366-6ed3-447c-9f51-bbbbd846a4e4)

**Comment by Frodo45127** [comment] 2023-08-08 13:51
Ignore it. It's because in the last schema update a ton of fixes were pushed for all games, including a fix for that column's reference which was pointing to the wrong column. The problem is the column it should point to also has it's name wrong, and the fix for that comes in a future schema update.

**Comment by Frodo45127** [comment] 2023-08-15 00:31
Fixed with the update I just pushed.

**Closed by Frodo45127** 2023-08-15 00:31 UTC
