### ISSUE TITLE
Certain .tsv Files exported by RPFM fail in reimporting them immediately afterwards

### ISSUE THREAD

**Issue by wolphyx** [Frodo45127/rpfm#20] opened 2018-11-10 16:41 UTC
There is probably a bug in the .tsv or .loc parsing logic somewhere. The following bug can be reproduced with the NordoGerman mod for Rome II, which contains a .loc file with a multitude of translations.

I can open the pack file with RPFM and export the .loc as .tsv. But when I reimport the same exported .tsv file immediately afterwards, the parser complains with the following error: 

This TSV file has an error in the row 4747, field 2 (both starting at 1). Please, check it and make sure the value in that field is a valid value for that column.

Which is strange because it had no problem opening and exporting the same file before. 
The respective row contains the following string: (The [TAB]s represents a Tab whitespace)

event_log_descriptions_event_content_diplo_war[TAB]%S     -     %S[TAB]true

Maybe there is a problem with the leading % symbol in the second column? Pack File Manager 5.0 can handle this exported .tsv without a problem and reimports it successfully (Apart from stripping all leading " like it always does -.-)

This occurs on the newest version 1.2.2. of RPFM. I hope you can look into it, as I much prefer to edit .loc files with RPFM if it weren't for this bug. Thanks in advance and keep up the good work!

**Comment by Frodo45127** [comment] 2018-11-11 18:52
The problem is not there, but here, a few rows below (I guess there are some more lines like this and it's confusing RPFM when getting the line number):
![imagen](https://user-images.githubusercontent.com/15714929/48316944-8f0e7f00-e5ea-11e8-8e5f-b880009b3bf3.png)
RPFM imports the TSV files row by row, and one of the entries has multiple lines. This seems to be an extension of certain issues that make working with \t and \n characters very difficult in loc files.

The fix is to escape them, and it's planned for the next version.

**Comment by wolphyx** [comment] 2018-11-12 23:44
Wonderful, nice to hear that! Btw I really like the new dark mode, it makes late night modding much more enjoyable. You're really doing a great job here. :)

**Comment by Frodo45127** [comment] 2018-11-17 14:02
And this is finally fixed in the develop branch so I guess it'll land in 1.3. One less bug to deal with.

**Closed by Frodo45127** 2018-11-17 14:02 UTC
