### ISSUE TITLE
Replace issue

### ISSUE THREAD

**Issue by NCISSky** [Frodo45127/rpfm#142] opened 2020-11-15 14:00 UTC
After I update to V2.3.3, if I want to use "replace all" function, it always crashed. Even I try to use the old version, this problem will remain the same(Now I have to find a way to fix it……).

**Comment by NCISSky** [comment] 2020-11-15 14:27
Now my RPFM will crashed in every version when I try to use the "Replace all" buttom...

**Comment by Frodo45127** [comment] 2020-11-15 14:27
do you have a crash log? The only crash I found related with the global search in 2.3.X was fixed in 2.3.2, and I've been unable to reproduce it since.

**Comment by NCISSky** [comment] 2020-11-15 14:31
Where can I find the crash log?
Right now whatever I use which version, when I try replace all, it only happen like this.
![QQ截图20201115222938](https://user-images.githubusercontent.com/73961703/99187555-3f8f5a80-2792-11eb-887f-9df408c66da2.png)
![QQ截图20201115222958](https://user-images.githubusercontent.com/73961703/99187558-40c08780-2792-11eb-98a5-bcec3df3ce97.png)

**Comment by Frodo45127** [comment] 2020-11-15 14:34
Go to game selected/open RPFM config folder and check if there are any toml files in the errors folder. Also, before hitting replace all, can you go to "about/about RPFM" and check that your version is indeed 2.3.2 or 2.3.3? I already had a few reports like this that turned out to be windows using an older version of the program when opening packfiles by doubleclicking them.

**Comment by NCISSky** [comment] 2020-11-15 14:38
![QQ截图20201115223722](https://user-images.githubusercontent.com/73961703/99187704-263ade00-2793-11eb-9eae-47ffde4bffed.png)
![QQ截图20201115223705](https://user-images.githubusercontent.com/73961703/99187706-276c0b00-2793-11eb-817b-77094aea5a12.png)
It's a V2.3.3, and no file in "errors"

**Comment by NCISSky** [comment] 2020-11-15 14:47
To Frodo45127
I find a interesting pattern(in my case, not so interesting)
When I want to replace a shorter word, it would not crashed, but when I try to replace a longer word, it will crashed.

**Comment by NCISSky** [comment] 2020-11-15 14:50
![QQ截图20201115224903](https://user-images.githubusercontent.com/73961703/99188035-e674f600-2794-11eb-853a-6699856bcae5.png)
![QQ截图20201115224908](https://user-images.githubusercontent.com/73961703/99188036-e83eb980-2794-11eb-88a9-cb85d4b5891f.png)
![QQ截图20201115224936](https://user-images.githubusercontent.com/73961703/99188038-ea087d00-2794-11eb-9f64-ba51970718b6.png)
![QQ截图20201115224949](https://user-images.githubusercontent.com/73961703/99188041-ebd24080-2794-11eb-8f26-e454f0eba284.png)

**Comment by NCISSky** [comment] 2020-11-15 15:04
I have try different mod, it always happen to be when I try to use a longer word to replace old word, then RPFM will crashed immediately.

**Comment by Frodo45127** [comment] 2020-11-15 16:32
Ok, found the problem. The replace code is getting trap in an infinite replace loop if you're not using regex and the replace pattern contains a match of the replaced pattern.... You can try to bypass it using regex search for now. And for what I see, this is a bug from at least 2.1/2.0....

**Comment by NCISSky** [comment] 2020-11-15 17:14
> 
> 
> Ok, found the problem. The replace code is getting trap in an infinite replace loop if you're not using regex and the replace pattern contains a match of the replaced pattern.... You can try to bypass it using regex search for now. And for what I see, this is a bug from at least 2.1/2.0....

Finally it work, thank a lot.

**Closed** 2020-11-17 19:56 UTC
