### ISSUE TITLE
New version of RPFM CLI is not backward compatible when importing color columns from previous versions of ETW tsv tables

### ISSUE THREAD

**Issue by ilia-r-s** [Frodo45127/rpfm#291] opened 2024-06-16 19:23 UTC
For instance, when I'm trying to import factions.tsv created using an older RPFM version export feature, it has separate columns for R, G and B faction colors.

Now, when I'm trying to import that tsv with a new version of RPFM CLI, it isn't capable of handling the old RGB columns and converting them to hex, and all new hex columns are filled with zeros, making all factions black on the minimap.

**Comment by Frodo45127** [comment] 2024-06-16 20:29
Not a bug. Rather, is how schema updates have always worked: if a definition changes (in this case the 3 colour columns have been merged into a single column so rpfm can use the colour selector widget for it), you'll need to re-export the table tsv file in order to get it updated with the new definition. Importing the old one will result in the columns not present on it (in this case, the new colour column) getting a default value (that black colour).

Usually these kind of changes are only done on game updates, or in schema fixes (which is this case). So.... you'll have to re-export the tsv to get it updated with the new column.

**Closed** 2024-12-26 15:40 UTC
