### ISSUE TITLE
Error while checking new updates from about menu wqith new install RPFM ver 1.6.2

### ISSUE THREAD

**Issue by Stix-09** [Frodo45127/rpfm#152] opened 2021-01-25 03:53 UTC
**Describe your problem**

New download and install of RPFM ver 1.6.2 (Qt ver 5.12.3)
Followed manual setup guide and setup programs preferences.
_Guide also states it should prompt for new schema (it doesn't do that BTW either:-)_

After saving preferenced, used about menu to 
1) check for program updates (it is latest download but tested this anyway)

returns popup window "Update checker"  with following text

> Error while checking new updates
> There has been a problem when getting the lastest released version number, or the current version number. That means I fucked up the last release title. If you see this, please report it here: https://github.com/Frodo45127/rpfm/issues

2)then tried to update Schema using program about menu 
also returns popup window "Update Schema Checker" with following text

> Error while checking new updates :(
> If you see this message, there has been a problem with your connection to the Github.com server. Please, make sure you can access to https://api.github.com and try again.

Tried 3 times same results
The Web page https://api.github.com/ returns following text

> {
>   "current_user_url": "https://api.github.com/user",
>   "current_user_authorizations_html_url": "https://github.com/settings/connections/applications{/client_id}",
>   "authorizations_url": "https://api.github.com/authorizations",
>   "code_search_url": "https://api.github.com/search/code?q={query}{&page,per_page,sort,order}",
>   "commit_search_url": "https://api.github.com/search/commits?q={query}{&page,per_page,sort,order}",
>   "emails_url": "https://api.github.com/user/emails",
>   "emojis_url": "https://api.github.com/emojis",
>   "events_url": "https://api.github.com/events",
>   "feeds_url": "https://api.github.com/feeds",
>   "followers_url": "https://api.github.com/user/followers",
>   "following_url": "https://api.github.com/user/following{/target}",
>   "gists_url": "https://api.github.com/gists{/gist_id}",
>   "hub_url": "https://api.github.com/hub",
>   "issue_search_url": "https://api.github.com/search/issues?q={query}{&page,per_page,sort,order}",
>   "issues_url": "https://api.github.com/issues",
>   "keys_url": "https://api.github.com/user/keys",
>   "label_search_url": "https://api.github.com/search/labels?q={query}&repository_id={repository_id}{&page,per_page}",
>   "notifications_url": "https://api.github.com/notifications",
>   "organization_url": "https://api.github.com/orgs/{org}",
>   "organization_repositories_url": "https://api.github.com/orgs/{org}/repos{?type,page,per_page,sort}",
>   "organization_teams_url": "https://api.github.com/orgs/{org}/teams",
>   "public_gists_url": "https://api.github.com/gists/public",
>   "rate_limit_url": "https://api.github.com/rate_limit",
>   "repository_url": "https://api.github.com/repos/{owner}/{repo}",
>   "repository_search_url": "https://api.github.com/search/repositories?q={query}{&page,per_page,sort,order}",
>   "current_user_repositories_url": "https://api.github.com/user/repos{?type,page,per_page,sort}",
>   "starred_url": "https://api.github.com/user/starred{/owner}{/repo}",
>   "starred_gists_url": "https://api.github.com/gists/starred",
>   "user_url": "https://api.github.com/users/{user}",
>   "user_organizations_url": "https://api.github.com/user/orgs",
>   "user_repositories_url": "https://api.github.com/users/{user}/repos{?type,page,per_page,sort}",
>   "user_search_url": "https://api.github.com/search/users?q={query}{&page,per_page,sort,order}"
> }

**Comment by Stix-09** [comment] 2021-01-25 04:07
![image](https://user-images.githubusercontent.com/60739090/105660386-c0579900-5f2f-11eb-87d1-5e4b3cef4776.png)
![Uploading image.png…]()

**Comment by Frodo45127** [comment] 2021-01-30 03:22
1.6.2 is an unsupported version, and all update checkers were rewritten in the 2.X releases, leaving 1.6.2 update checker working only up to 2.1. After that, if you didn't updated before, the update checker would fail. So, not a bug really.

**Comment by Frodo45127** [comment] 2021-02-10 19:51
As there are no more questions and I'm cleaning this a bit, I'll close this one.

**Closed by Frodo45127** 2021-02-10 19:51 UTC
