### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by pconners69** [Frodo45127/rpfm#112] opened 2020-06-01 11:32 UTC
Great tool and thanks for the upgrade. With 2.0 though I'm getting this very strange bug. On some tables (seems to be more common with the bigger tables I think?) when I click on one of the fields the table will resort and jump to a different record. It might even select a bunch of rows or cells. I can sort the table, scroll and view etc, but as soon as I click in the table it can go haywire. Ver 1.6.2 is still working fine (although some of the schemas are out of date). Any idea what might be causing this? Thanks, Peter

**Comment by Frodo45127** [comment] 2020-06-01 16:49
What version are you using? That bug was in one of the old 2.0 betas, but was fixed about a month ago.

**Comment by pconners69** [comment] 2020-06-02 02:50
Thanks for the reply. I downloaded from the link that came up from the prompt to update in ver 1.6.2, the about info says ver 2.0.0. I’ll redownload direct from the site and see if it fixes it.

[cid:image002.png@01D638DC.5FC64C00]

**Comment by pconners69** [comment] 2020-06-02 03:32
Just redownloaded from the GitHub site, same issue. Have checked for updates using RPFM, it says up to date. Odd...

**Comment by Frodo45127** [comment] 2020-06-02 20:47
Do you know a table where I can reliably reproduce this?

**Comment by pconners69** [comment] 2020-06-03 03:53
It happens on many tables, particularly the larger ones. Two I know for sure are land_units_tables and unit_set_to_unit_junctions_tables (two tables I use frequently). It’s odd, if I click just on the first page of the table (about 50 rows for me) it’s fine, if I scroll down and click it starts to go haywire. BTW, I just installed it on a second computer and found the same issue.

Additionally, I found that if I try and rename multiple tables at once it crashes the program, this works fine in 1.6.2.

Finally I subscribed to be a patron the other day, felt bad asking for tech support on a free product. Keep up the good work.

**Comment by Frodo45127** [comment] 2020-06-05 18:21
Should have been fixed in 2.0.1 but, as I was unable to reproduce it, I'll leave this open. Just in case it's still there.

**Comment by pconners69** [comment] 2020-06-06 02:43
I just checked out 2.0.2 and all seems good. Again, great tool and thanks for your efforts.

Peter

**Comment by Frodo45127** [comment] 2020-06-06 08:04
Ok, closing the issue then. Hopefully it doesn´t re-appear a third time this one... The ones you cannot reproduce are always the more problematic to fix....

**Closed by Frodo45127** 2020-06-06 08:04 UTC
